GWWC login template updates
centre-for-effective-altruism/auth0-rules pull request #39
Opened 2024-01-15 14:45 UTC by mordaroso

In the login screen of Auth0
* don't mention ea.org account in subtitle
* use GWWC copy and links in footer callouts

<img width="724" alt="Screenshot 2024-01-15 at 15 42 26" src="https://github.com/centre-for-effective-altruism/auth0-rules/assets/15565/ce676b3c-7e8e-463a-ae86-9dbbb2ed5249">

Additionally rename the GWWC app to "Giving What We Can" (remove mention of 'Lyra')

2024-01-15 20:26 UTC, sarahbaka commented on templates/login.liquid
> +        text-indent: -9999999px;
What does the `-9999999px;` do exactly, in the updated design?

2024-01-15 20:33 UTC, sarahbaka requested changes

2024-01-15 20:33 UTC, sarahbaka commented on templates/login.liquid
> +        text-indent: -9999999px;
[Query] What does the `-9999999px;` do exactly, in the updated design?

2024-01-15 20:33 UTC, sarahbaka commented on templates/login.liquid
> +        By creating an <a href="https://www.givingwhatwecan.org/" target="_blank" rel="noreferrer">Giving What We Can</a> account,
```suggestion
        By creating a <a href="https://www.givingwhatwecan.org/" target="_blank" rel="noreferrer">Giving What We Can</a> account,
```

2024-01-15 20:33 UTC, sarahbaka commented on templates/login.liquid
[Query] How exactly is the "Log in to EffectiveAltruism.org to continue to ..." copy removed? I see the removal of the application name  'Giving What We Can - Lyra' in the `cli/manifests.ts` file, but not the removal of "Log in to EffectiveAltruism.org to continue to ..." in the PR diffs. Does simply adding a new `header p:after {` section override this copy?

2024-01-15 20:36 UTC, sarahbaka reviewed
@mordaroso Should be good to be deployed soon, just a sanity check question about where/how "Log in to EffectiveAltruism.org to continue to ..." is removed and a minor copy correction 🙂

2024-01-16 08:10 UTC, mordaroso commented on templates/login.liquid
> +        text-indent: -9999999px;
It is a [common pattern](https://stackoverflow.com/a/22054588) to hide or replace text. We use the same logic already to remove the "Welcome" and show the GWWC logo (see changes on `h1`).

Here in this case it hides the existing text in the `header p` which is "Login to EffectiveAltruism.org to continue to Giving What We Can" and the `header p:after` adds the new text.

2024-01-16 08:15 UTC, mordaroso commented on templates/login.liquid
Yes exactly. It first hides the existing text (see css for `header p`) and then adds the new content as `header p:after`. It's a bit of a hack but there seems no way that we use conditionals in the "[Universal Login Custom Text](https://manage.auth0.com/dashboard/us/effectivealtruism/custom_text)" 
![Uploading Screenshot 2024-01-16 at 09.13.42.png…]()


As we only want to change the text for the GWWC login screen and keep it for the rest (EA Forum, EAG, etc) we use css to replace it.

2024-01-16 09:45 UTC, sarahbaka commented on templates/login.liquid
Ahh, I see now - thanks for clarifying!

2024-01-16 09:45 UTC, sarahbaka approved these changes

2024-01-16 17:29 UTC, merged